In [2]:
#List 데이터 타입
l = [[1,2,3],[4,5,6]]
type(l)

list

In [3]:
#print를 사용하지 않으면 한 번에 한 리스트만 출력가능
l[0]
l[1]

[4, 5, 6]

In [4]:
print(l[0])
print(l[1])

[1, 2, 3]
[4, 5, 6]


In [5]:
print(l[0][0])
print(l[0][1])
print(l[0][2])

1
2
3


In [6]:
for i, a in enumerate(l) : 
    for j, b in enumerate(a) :
        print(l[i][j])
# a, b 변수는 리스트 안 값을 버리고 index만 가져오기 위한 변수

1
2
3
4
5
6


In [7]:
import numpy as np
np.__version__

'2.3.5'

In [8]:
print(np.ndarray)
np.ndarray.__name__

<class 'numpy.ndarray'>


'ndarray'

In [9]:
type(np.ndarray.var)

method_descriptor

In [10]:
# 1) np.array
# 1차원 배열
vec = np.array([1,2,3,4,5])
print(vec)

[1 2 3 4 5]


In [ ]:
# 2차원 배열

In [12]:
mat = np.array([[10,20,30],[60,70,80]])
print(mat)

[[10 20 30]
 [60 70 80]]


In [13]:
print("vec의 타입 :", type(vec))
print("mat의 타입 :", type(mat))

vec의 타입 : <class 'numpy.ndarray'>
mat의 타입 : <class 'numpy.ndarray'>


In [15]:
# 축의 개수 ndim, 크기 shape
print("mat의 축의 개수 :", mat.ndim)
print("mat의 크기 :", mat.shape)

mat의 축의 개수 : 2
mat의 크기 : (2, 3)


In [17]:
# 2) ndarray의 초기화
# 모든 값이 0인 행렬 생성 : np.zeros()
zero_mat = np.zeros((2,3))
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
# 모든 값이 1인 행렬 생성 : np.ones()
one_mat = np.ones((2,3))
print(one_mat)

[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# 모든 값이 특정 상수인 행렬 생성 : np.full()
same_value_mat = np.full((2,2),7)
print(same_value_mat)

[[7 7]
 [7 7]]


In [22]:
# 대각선 값이 1이고 나머지가 0인 행렬 생성 : np.eye
eye_mat = np.eye(3)
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
# 임의의 값으로 채워진 행렬 생성 : np.random.random()
random_mat = np.random.random((2,2))
print(random_mat)

[[0.64560065 0.44848058]
 [0.75175462 0.68523304]]


In [27]:
# 3) np.arange
# 0부터 n-1까지의 값을 가지는 행렬 생성 : np.arange(n)
range_vec1 = np.arange(10)
print(range_vec1)

# n부터 m-1까지의 값을 o만큼의 간격으로 행렬 생성 : np.arange(n,m,o)
range_vec2 = np.arange(1,10,2)
print(range_vec2)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [32]:
# 4) np.reshape
# 내부 데이터 변경하지 않으면서 배열의 구조 변경 : np.reshape(행,열))
reshape_mat = np.array(np.arange(1,31).reshape((3,10)))
print(reshape_mat)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
